server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/chatapp
spring.datasource.username=harshsharma
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=ChatAppSecretKey2024SuperLongAndSecureForJWT!
app.jwt.expiration-ms=86400000

logging.level.com.chatapp=INFO
